'use client';
import Link from 'next/link';
import {useEffect,useRef} from 'react';
import {imgSrc,letter} from '@/lib/format';
import {CATEGORY_ORDER} from '@/lib/categories';
import type {CategoryTreeNode} from '@/lib/products';
interface Sub{category:string;subName:string;count:number;thumb:string|null;}
interface Props{tree:Record<string,CategoryTreeNode[]>;}
const VISIBLE_TILES=7;const GAP_PX=20;const SLIDE_STEP=3;const INTERVAL_MS=8000;
function tilePitch(el:HTMLElement):number{const first=el.firstElementChild as HTMLElement|null;if(!first)return 0;return first.getBoundingClientRect().width+GAP_PX;}
export function CategoryTiles({tree}:Props){
const subs:Sub[]=[];const orderedCats=[...CATEGORY_ORDER.filter((c)=>tree[c]),...Object.keys(tree).filter((c)=>!CATEGORY_ORDER.includes(c))];
for(const cat of orderedCats){for(const s of tree[cat]??[]){const n=s.subName.trim();if(!n||n.toLowerCase()==='sample'||/^[-–—]+$/.test(n)||s.count===0)continue;subs.push({category:cat,subName:s.subName,count:s.count,thumb:s.thumb});}}
const scrollRef=useRef<HTMLDivElement>(null);const paused=useRef(false);
useEffect(()=>{const id=setInterval(()=>{if(paused.current)return;const el=scrollRef.current;if(!el)return;const max=el.scrollWidth-el.clientWidth;if(el.scrollLeft+2>=max){el.scrollTo({left:0,behavior:'smooth'});}else{el.scrollBy({left:tilePitch(el)*SLIDE_STEP,behavior:'smooth'});}},INTERVAL_MS);return()=>clearInterval(id);},[]);
const scroll=(dir:-1|1)=>{const el=scrollRef.current;if(!el)return;el.scrollBy({left:tilePitch(el)*SLIDE_STEP*dir,behavior:'smooth'});};
return(<div className="pt-10 pb-0"><div className="max-w-site mx-auto px-[6mm] md:px-[1.5cm] relative"><button type="button" onClick={()=>scroll(-1)} aria-label="Previous" className="absolute left-1 md:left-[1.5cm] top-[70px] -translate-y-1/2 z-10 hidden md:grid w-11 h-11 rounded-full bg-white shadow-md place-items-center text-ink text-2xl hover:bg-brand hover:text-white transition">‹</button><button type="button" onClick={()=>scroll(1)} aria-label="Next" className="absolute right-1 md:right-[1.5cm] top-[70px] -translate-y-1/2 z-10 hidden md:grid w-11 h-11 rounded-full bg-white shadow-md place-items-center text-ink text-2xl hover:bg-brand hover:text-white transition">›</button><div ref={scrollRef} onMouseEnter={()=>(paused.current=true)} onMouseLeave={()=>(paused.current=false)} className="flex gap-3 md:gap-5 overflow-x-auto no-scrollbar pt-2 pb-3 scroll-smooth" style={{scrollSnapType:'x mandatory'}}>{subs.map((s)=>(<Link key={`${s.category}/${s.subName}`} href={`/shop?cat=${encodeURIComponent(s.category)}&sub=${encodeURIComponent(s.subName)}`} className="kk-cat-tile group relative z-0 hover:z-[1] shrink-0 flex flex-col items-center gap-1.5 md:gap-2.5 text-center hover:-translate-y-0.5 transition" style={{scrollSnapAlign:'start',flex:`0 0 calc((100% - ${(VISIBLE_TILES-1)*GAP_PX}px) / ${VISIBLE_TILES})`}}><div className="w-full rounded-full overflow-hidden flex items-center justify-center p-3 md:p-4 transition border border-line group-hover:border-brand" style={{aspectRatio:'1 / 1',background:s.thumb?'#fff':'linear-gradient(180deg, #F5E6CF 0%, #E6C8A8 100%)'}}>{s.thumb?(/* Reverted from next/image to plain <img> 2026-05-23 — Vercel image-optimizer was returning broken/missing tiles for some category thumbs in production. The thumbs are tiny (~130px) so we don't really need on-the-fly optimisation; explicit width/height + lazy still avoid CLS. flex + max-w/max-h + object-contain fits the whole image without cropping regardless of its aspect ratio. */<img src={imgSrc(s.thumb, 300)} alt={s.subName} width={200} height={175} loading="lazy" className="max-w-full max-h-full object-contain"/>):(<span className="text-5xl font-head font-black text-brand opacity-55">{letter(s.subName)}</span>)}</div><div className="font-head font-semibold text-[11px] md:text-[12.5px] text-ink leading-tight px-0.5 md:px-1 line-clamp-2 min-h-[2.4em]">{s.subName}</div></Link>))}</div></div></div>);}
