
'use client';
import Link from 'next/link';
import {useState} from 'react';
import {imgSrc,inr,letter,savingsPercent} from '@/lib/format';
import {addToCart,openDrawer,useCart} from '@/lib/cart';
import {openAuth,useAuth} from '@/lib/useAuth';
import {toggleWishlist,useIsInWishlist} from '@/lib/wishlist';
import {pseudoRating,Stars} from '@/lib/rating';
import type {PublicProduct} from '@/lib/products';
interface Props{product:PublicProduct;badge?:'bestseller'|'new'|null;}
export function ProductCard({product:p,badge}:Props){
const save=savingsPercent(p.price,p.mrp);const rating=pseudoRating(p.sku);const{loggedIn}=useAuth();const saved=useIsInWishlist(p.sku);
// Tick counter forces the heart svg to remount on every click so the
// kk-heart-pop CSS keyframe always re-triggers (animations don't
// replay when the same element + same class stays mounted).
const [heartTick,setHeartTick]=useState(0);
const {items:cartItems}=useCart();const qty=cartItems.find(i=>i.sku===p.sku)?.qty??0;
// Mirrors AddToInquiryButton on the PDP. The checkout API already rejects
// out-of-stock lines with a 409, so no bad order can be placed — but without
// this the buyer only finds out AFTER filling in their address.
const outOfStock=typeof p.stock==='number'&&p.stock<=0;
function gated(action:()=>void){if(loggedIn){action();}else{openAuth({onSuccess:action});}}
return(<div className="product-card">{badge==='bestseller'&&<span className="product-badge">Best Seller</span>}{badge==='new'&&<span className="product-badge">New</span>}{save>=20&&(<span className="product-badge product-badge-discount" style={{top:badge?40:10}}>{save}% OFF</span>)}<button type="button" aria-label={saved?'Remove from wishlist':'Add to wishlist'} aria-pressed={saved} onClick={(e)=>{e.preventDefault();e.stopPropagation();toggleWishlist(p);setHeartTick(t=>t+1);}} className={`absolute top-2 right-2 z-[3] w-9 h-9 rounded-full grid place-items-center bg-white/95 border border-line shadow-sm transition hover:scale-105 ${saved?'text-brand':'text-muted hover:text-brand'}`}><svg key={heartTick} className={heartTick>0?'kk-heart-pop':''} viewBox="0 0 24 24" width="18" height="18" fill={saved?'currentColor':'none'} stroke="currentColor" strokeWidth="2"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg></button><Link href={`/product/${encodeURIComponent(p.sku)}`} aria-label={p.name} className={`product-img block ${p.imageUrl?'bg-white':''}`}>{p.imageUrl?(<>{/* Plain <img> after Vercel image-optimizer revert. decoding="async" lets the browser decode the image off the main thread so similar-products grids don't block scroll. */}<img src={imgSrc(p.imageUrl, 500)} alt={p.name} width={500} height={500} loading="lazy" decoding="async" className={`kk-img-base${p.hoverImage?' kk-img-swap':''}`}/>{p.hoverImage&&(/* Decorative: the base img already carries the product name, so an empty alt keeps screen readers from announcing it twice. */<img src={imgSrc(p.hoverImage, 500)} alt="" aria-hidden="true" width={500} height={500} loading="lazy" decoding="async" className="kk-img-alt"/>)}</>):(<span className="product-img-letter">{letter(p.name)}</span>)}</Link><div className="p-4 flex flex-col gap-1.5 flex-1"><div className="text-[10.5px] text-muted tracking-widest uppercase font-semibold">Kitchenary Kart</div><div className="text-sm font-bold text-ink line-clamp-2 leading-snug min-h-[2.7em]"><Link href={`/product/${encodeURIComponent(p.sku)}`} className="hover:text-brand">{p.name}</Link></div><div className="flex items-center gap-1.5"><Stars value={rating.stars}/><span className="text-[13px] text-ink font-medium whitespace-nowrap">{rating.stars.toFixed(1)} ({rating.count})</span></div>{/* Specs are hidden on mobile (`hidden sm:flex`) — they made the card too tall
    on small screens. Phones keep title/rating/price/actions only; the full
    specs are one tap away on the PDP. */}
{(p.capacity||p.power)?(<div className="text-[11.5px] text-muted hidden sm:flex flex-wrap gap-2.5 mt-1">{p.capacity&&(<span><strong className="text-ink font-semibold">Cap</strong> {p.capacity}</span>)}{p.power&&(<span><strong className="text-ink font-semibold">Power</strong> {p.power}</span>)}</div>):p.material?(/* Non-appliance products (mats, trays, tableware) have no Cap/Power — show Material instead so the card still carries a useful spec. */<div className="text-[11.5px] text-muted hidden sm:flex mt-1 line-clamp-1"><span><strong className="text-ink font-semibold">Material</strong> {p.material}</span></div>):null}<div className="mt-auto pt-2"><div className="font-head text-lg font-bold text-ink leading-none">{inr(p.price)}</div>{/* Second row is ALWAYS rendered (min-height reserved) so the price block
   is the same height whether or not there's an MRP/discount — keeps every
   card in a row aligned instead of the MRP jumping up/down by amount width. */}<div className="flex items-center gap-2 mt-1 min-h-[16px]">{(p.mrp??0)>p.price&&(<span className="text-[13px] text-muted line-through">{inr(p.mrp)}</span>)}{save>0&&(<span className="text-[11px] font-bold text-success tracking-wide">SAVE {save}%</span>)}</div></div></div><div className="kk-card-actions flex gap-2 px-4 pb-4">{outOfStock?(<button type="button" disabled aria-disabled="true" className="btn-small btn-small-outline !py-2 flex-1 opacity-60 cursor-not-allowed">Out of Stock</button>):(<>{/* Cart button just adds +1 on every click (no ± stepper — saves space
     and stops the wide stepper wrapping "Buy Now" on narrow phones). The
     badge shows the running count so the buyer sees it climb. */}<button type="button" aria-label={qty>0?`In cart: ${qty}. Add one more`:'Add to cart'} title="Add to cart" className="btn-small btn-small-outline !flex-none !py-2 relative w-11 grid place-items-center" onClick={()=>gated(()=>addToCart(p))}><svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/></svg>{qty>0&&(<span className="absolute -top-1.5 -right-1.5 min-w-[18px] h-[18px] px-1 rounded-full bg-brand text-white text-[10px] font-head font-bold grid place-items-center leading-none tabular-nums">{qty>99?'99+':qty}</span>)}</button><button type="button" className="btn-small btn-small-primary !py-2" onClick={()=>gated(()=>{addToCart(p);openDrawer();})}>Buy Now</button></>)}</div></div>);}
